/*
	The management script uses this symbol to identify the fake libXrandr version
*/
int _is_fake_xrandr = 1;

/*
	We use this XID modifier to flag outputs and CRTCs as
	fake by adding a counter in the first few bits:
	 · xid & ~XID_SPLIT_MASK is the xid of the original output
	 · xid >> XID_SPLIT_SHIFT is the counter identifying a virtual, split screen

	On the choice: A typical XID is of the form
	 client_id | (xid_mask & arbitrary value),
	according to the documentation of the X-Resource extension. On my system,
	 xid_mask = 0x001FFFFF
	and client_id == 0 for all reources mentioned in the RandR protocol.
	All we need to do is to choose XID_SPLIT_MASK such that
	XID_SPLIT_MASK & xid_mask == 0.
*/
#define XID_SPLIT_SHIFT 21
#define XID_SPLIT_MASK  0x7FE00000

/*
	Generated by ./configure:
*/
#include "config.h"
